/**
 * Indian Food Seed Database
 *
 * Nutrition values are approximate and based on IFCT (Indian Food Composition Tables),
 * USDA, and commonly referenced Indian nutrition sources.
 * All values are per the stated serving size.
 */

export interface SeedFoodItem {
  name: string;
  name_local?: string;
  category: string;
  subcategory?: string;
  serving_size_g: number;
  serving_unit: string;
  calories_per_serving: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  fiber_g: number;
  is_veg: boolean;
  is_egg: boolean;
  is_vegan: boolean;
  preferred_brand?: string;
}

export const SEED_FOODS: SeedFoodItem[] = [
  // ============================================================
  // GRAINS
  // ============================================================
  {
    name: "White Rice (cooked)",
    name_local: "Chawal",
    category: "grain",
    subcategory: "rice",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 130,
    protein_g: 2.7,
    carbs_g: 28,
    fat_g: 0.3,
    fiber_g: 0.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Brown Rice (cooked)",
    name_local: "Brown Chawal",
    category: "grain",
    subcategory: "rice",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 112,
    protein_g: 2.6,
    carbs_g: 24,
    fat_g: 0.9,
    fiber_g: 1.8,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Roti / Chapati",
    name_local: "Roti",
    category: "grain",
    subcategory: "flatbread",
    serving_size_g: 30,
    serving_unit: "piece",
    calories_per_serving: 70,
    protein_g: 2.5,
    carbs_g: 13,
    fat_g: 0.9,
    fiber_g: 1.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Paratha (plain)",
    name_local: "Paratha",
    category: "grain",
    subcategory: "flatbread",
    serving_size_g: 60,
    serving_unit: "piece",
    calories_per_serving: 180,
    protein_g: 4,
    carbs_g: 25,
    fat_g: 7,
    fiber_g: 1.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Dosa (plain)",
    name_local: "Dosa",
    category: "grain",
    subcategory: "south_indian",
    serving_size_g: 80,
    serving_unit: "piece",
    calories_per_serving: 120,
    protein_g: 3.5,
    carbs_g: 18,
    fat_g: 3.7,
    fiber_g: 0.8,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Idli",
    name_local: "Idli",
    category: "grain",
    subcategory: "south_indian",
    serving_size_g: 30,
    serving_unit: "piece",
    calories_per_serving: 39,
    protein_g: 1.2,
    carbs_g: 7.8,
    fat_g: 0.2,
    fiber_g: 0.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Upma",
    name_local: "Upma",
    category: "grain",
    subcategory: "south_indian",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 130,
    protein_g: 3.5,
    carbs_g: 18,
    fat_g: 4.8,
    fiber_g: 1.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Poha",
    name_local: "Poha / Aval",
    category: "grain",
    subcategory: "breakfast",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 158,
    protein_g: 3.2,
    carbs_g: 28,
    fat_g: 3.5,
    fiber_g: 1.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Oats (raw)",
    category: "grain",
    subcategory: "cereal",
    serving_size_g: 50,
    serving_unit: "g",
    calories_per_serving: 190,
    protein_g: 6.5,
    carbs_g: 34,
    fat_g: 3.5,
    fiber_g: 5.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Soaked Oats (overnight)",
    category: "grain",
    subcategory: "cereal",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 140,
    protein_g: 5,
    carbs_g: 25,
    fat_g: 2.5,
    fiber_g: 3.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Bread Wheat (1 slice)",
    name_local: "Bread",
    category: "grain",
    subcategory: "bread",
    serving_size_g: 30,
    serving_unit: "slice",
    calories_per_serving: 75,
    protein_g: 2.7,
    carbs_g: 14,
    fat_g: 0.9,
    fiber_g: 1.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Protein Dosa (ID batter)",
    category: "grain",
    subcategory: "south_indian",
    serving_size_g: 150,
    serving_unit: "g",
    calories_per_serving: 185,
    protein_g: 8,
    carbs_g: 26,
    fat_g: 5,
    fiber_g: 1.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
    preferred_brand: "iD Fresh",
  },
  {
    name: "Ragi Mudde",
    name_local: "Ragi Mudde",
    category: "grain",
    subcategory: "millet",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 110,
    protein_g: 3.5,
    carbs_g: 22,
    fat_g: 1.0,
    fiber_g: 3.6,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Little Millet (cooked)",
    name_local: "Samai / Kutki",
    category: "grain",
    subcategory: "millet",
    serving_size_g: 70,
    serving_unit: "g",
    calories_per_serving: 78,
    protein_g: 2.5,
    carbs_g: 15,
    fat_g: 0.7,
    fiber_g: 2.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Foxtail Millet (cooked)",
    name_local: "Kangni / Thinai",
    category: "grain",
    subcategory: "millet",
    serving_size_g: 70,
    serving_unit: "g",
    calories_per_serving: 80,
    protein_g: 3,
    carbs_g: 15,
    fat_g: 0.8,
    fiber_g: 2.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Pearl Millet (cooked)",
    name_local: "Bajra",
    category: "grain",
    subcategory: "millet",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 119,
    protein_g: 3.4,
    carbs_g: 23,
    fat_g: 1.7,
    fiber_g: 2.3,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // DALS & LEGUMES
  // ============================================================
  {
    name: "Toor Dal (cooked)",
    name_local: "Toor Dal / Arhar Dal",
    category: "dal",
    subcategory: "lentil",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 91,
    protein_g: 5.4,
    carbs_g: 14,
    fat_g: 1.5,
    fiber_g: 2.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Moong Dal (cooked)",
    name_local: "Moong Dal",
    category: "dal",
    subcategory: "lentil",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 86,
    protein_g: 6.2,
    carbs_g: 13,
    fat_g: 0.5,
    fiber_g: 3.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Masoor Dal (cooked)",
    name_local: "Masoor Dal",
    category: "dal",
    subcategory: "lentil",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 93,
    protein_g: 6.8,
    carbs_g: 14,
    fat_g: 0.4,
    fiber_g: 2.8,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Chana Dal (cooked)",
    name_local: "Chana Dal",
    category: "dal",
    subcategory: "lentil",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 100,
    protein_g: 6.3,
    carbs_g: 15,
    fat_g: 1.8,
    fiber_g: 4.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Rajma (cooked)",
    name_local: "Rajma",
    category: "dal",
    subcategory: "legume",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 127,
    protein_g: 8.7,
    carbs_g: 22,
    fat_g: 0.5,
    fiber_g: 6.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Chole / Chickpeas (cooked)",
    name_local: "Chole / Kabuli Chana",
    category: "dal",
    subcategory: "legume",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 119,
    protein_g: 7,
    carbs_g: 20,
    fat_g: 2.6,
    fiber_g: 5.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Black Gram / Urad Dal (cooked)",
    name_local: "Urad Dal",
    category: "dal",
    subcategory: "lentil",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 95,
    protein_g: 6,
    carbs_g: 14,
    fat_g: 1.4,
    fiber_g: 3.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Soya Chunks (cooked)",
    name_local: "Soya Badi",
    category: "dal",
    subcategory: "soy",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 156,
    protein_g: 17,
    carbs_g: 10,
    fat_g: 5,
    fiber_g: 4.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Sprouts Moong",
    name_local: "Ankurit Moong",
    category: "dal",
    subcategory: "sprout",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 30,
    protein_g: 3.2,
    carbs_g: 4.3,
    fat_g: 0.2,
    fiber_g: 1.8,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Sprouts Mixed",
    name_local: "Mixed Ankurit",
    category: "dal",
    subcategory: "sprout",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 60,
    protein_g: 4.5,
    carbs_g: 8,
    fat_g: 0.5,
    fiber_g: 2.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Lobia / Black Eyed Peas (cooked)",
    name_local: "Lobia",
    category: "dal",
    subcategory: "legume",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 116,
    protein_g: 7.7,
    carbs_g: 21,
    fat_g: 0.5,
    fiber_g: 5.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // VEGETABLES
  // ============================================================
  {
    name: "Palak / Spinach",
    name_local: "Palak",
    category: "vegetable",
    subcategory: "leafy_green",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 23,
    protein_g: 2.9,
    carbs_g: 3.6,
    fat_g: 0.4,
    fiber_g: 2.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Bhindi / Okra",
    name_local: "Bhindi",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 33,
    protein_g: 1.9,
    carbs_g: 7,
    fat_g: 0.2,
    fiber_g: 3.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Lauki / Bottle Gourd",
    name_local: "Lauki / Sorakaya",
    category: "vegetable",
    subcategory: "gourd",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 15,
    protein_g: 0.6,
    carbs_g: 3.4,
    fat_g: 0.1,
    fiber_g: 0.6,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "French Beans",
    name_local: "Beans",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 31,
    protein_g: 1.8,
    carbs_g: 7,
    fat_g: 0.1,
    fiber_g: 3.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Cabbage",
    name_local: "Patta Gobi",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 25,
    protein_g: 1.3,
    carbs_g: 5.8,
    fat_g: 0.1,
    fiber_g: 2.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Cauliflower",
    name_local: "Phool Gobi",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 25,
    protein_g: 1.9,
    carbs_g: 5,
    fat_g: 0.3,
    fiber_g: 2.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Brinjal / Eggplant",
    name_local: "Baingan",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 25,
    protein_g: 1.0,
    carbs_g: 6,
    fat_g: 0.2,
    fiber_g: 3.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Carrot",
    name_local: "Gajar",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 41,
    protein_g: 0.9,
    carbs_g: 10,
    fat_g: 0.2,
    fiber_g: 2.8,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Beetroot",
    name_local: "Chukandar",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 43,
    protein_g: 1.6,
    carbs_g: 10,
    fat_g: 0.2,
    fiber_g: 2.8,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Capsicum",
    name_local: "Shimla Mirch",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 20,
    protein_g: 0.9,
    carbs_g: 4.6,
    fat_g: 0.2,
    fiber_g: 1.7,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Onion",
    name_local: "Pyaaz",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 40,
    protein_g: 1.1,
    carbs_g: 9,
    fat_g: 0.1,
    fiber_g: 1.7,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Tomato",
    name_local: "Tamatar",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 18,
    protein_g: 0.9,
    carbs_g: 3.9,
    fat_g: 0.2,
    fiber_g: 1.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Potato",
    name_local: "Aloo",
    category: "vegetable",
    subcategory: "root",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 77,
    protein_g: 2.0,
    carbs_g: 17,
    fat_g: 0.1,
    fiber_g: 2.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Sweet Potato",
    name_local: "Shakarkandi",
    category: "vegetable",
    subcategory: "root",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 86,
    protein_g: 1.6,
    carbs_g: 20,
    fat_g: 0.1,
    fiber_g: 3.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Mixed Vegetables (cooked)",
    name_local: "Mix Sabzi",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 65,
    protein_g: 2.5,
    carbs_g: 8,
    fat_g: 2.5,
    fiber_g: 3.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Drumstick",
    name_local: "Sahjan / Moringa",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 37,
    protein_g: 2.1,
    carbs_g: 8.5,
    fat_g: 0.2,
    fiber_g: 3.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Green Peas",
    name_local: "Matar",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 81,
    protein_g: 5.4,
    carbs_g: 14,
    fat_g: 0.4,
    fiber_g: 5.1,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Mushroom",
    name_local: "Khumbi",
    category: "vegetable",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 22,
    protein_g: 3.1,
    carbs_g: 3.3,
    fat_g: 0.3,
    fiber_g: 1.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // FRUITS
  // ============================================================
  {
    name: "Pomegranate",
    name_local: "Anaar",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 83,
    protein_g: 1.7,
    carbs_g: 19,
    fat_g: 1.2,
    fiber_g: 4.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Banana",
    name_local: "Kela",
    category: "fruit",
    serving_size_g: 120,
    serving_unit: "medium",
    calories_per_serving: 105,
    protein_g: 1.3,
    carbs_g: 27,
    fat_g: 0.4,
    fiber_g: 3.1,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Apple",
    name_local: "Seb",
    category: "fruit",
    serving_size_g: 180,
    serving_unit: "medium",
    calories_per_serving: 95,
    protein_g: 0.5,
    carbs_g: 25,
    fat_g: 0.3,
    fiber_g: 4.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Papaya",
    name_local: "Papita",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 43,
    protein_g: 0.5,
    carbs_g: 11,
    fat_g: 0.3,
    fiber_g: 1.7,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Watermelon",
    name_local: "Tarbooz",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 30,
    protein_g: 0.6,
    carbs_g: 8,
    fat_g: 0.2,
    fiber_g: 0.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Mango",
    name_local: "Aam",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 60,
    protein_g: 0.8,
    carbs_g: 15,
    fat_g: 0.4,
    fiber_g: 1.6,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Grapes (green)",
    name_local: "Angoor",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 67,
    protein_g: 0.7,
    carbs_g: 17,
    fat_g: 0.4,
    fiber_g: 0.9,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Orange",
    name_local: "Santra",
    category: "fruit",
    serving_size_g: 140,
    serving_unit: "medium",
    calories_per_serving: 62,
    protein_g: 1.2,
    carbs_g: 15,
    fat_g: 0.2,
    fiber_g: 3.1,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Guava",
    name_local: "Amrud",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 68,
    protein_g: 2.6,
    carbs_g: 14,
    fat_g: 1.0,
    fiber_g: 5.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Black Grapes",
    name_local: "Kala Angoor",
    category: "fruit",
    serving_size_g: 15,
    serving_unit: "g",
    calories_per_serving: 10,
    protein_g: 0.1,
    carbs_g: 2.6,
    fat_g: 0.1,
    fiber_g: 0.1,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Chikoo / Sapota",
    name_local: "Chikoo",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 83,
    protein_g: 0.4,
    carbs_g: 20,
    fat_g: 1.1,
    fiber_g: 5.3,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Pineapple",
    name_local: "Ananas",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 50,
    protein_g: 0.5,
    carbs_g: 13,
    fat_g: 0.1,
    fiber_g: 1.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Strawberry",
    category: "fruit",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 32,
    protein_g: 0.7,
    carbs_g: 7.7,
    fat_g: 0.3,
    fiber_g: 2.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // DAIRY
  // ============================================================
  {
    name: "Milk Full Fat",
    name_local: "Doodh",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "ml",
    calories_per_serving: 67,
    protein_g: 3.3,
    carbs_g: 4.8,
    fat_g: 3.9,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Milk Toned",
    name_local: "Toned Doodh",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "ml",
    calories_per_serving: 50,
    protein_g: 3.0,
    carbs_g: 4.8,
    fat_g: 1.5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Curd / Dahi",
    name_local: "Dahi",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 60,
    protein_g: 3.1,
    carbs_g: 4.7,
    fat_g: 3.3,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Greek Yogurt",
    category: "dairy",
    serving_size_g: 50,
    serving_unit: "g",
    calories_per_serving: 45,
    protein_g: 5,
    carbs_g: 2,
    fat_g: 1.5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Paneer",
    name_local: "Paneer",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 265,
    protein_g: 18,
    carbs_g: 3.6,
    fat_g: 20,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Low Fat Paneer",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 213,
    protein_g: 28,
    carbs_g: 3,
    fat_g: 10,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Farm Connect Paneer",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 250,
    protein_g: 20,
    carbs_g: 3.5,
    fat_g: 18,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
    preferred_brand: "Farm Connect",
  },
  {
    name: "Ghee",
    name_local: "Ghee",
    category: "dairy",
    subcategory: "fat",
    serving_size_g: 5,
    serving_unit: "tsp",
    calories_per_serving: 45,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Butter",
    name_local: "Makhan",
    category: "dairy",
    subcategory: "fat",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 72,
    protein_g: 0.1,
    carbs_g: 0,
    fat_g: 8.1,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Cheese Slice",
    category: "dairy",
    serving_size_g: 20,
    serving_unit: "slice",
    calories_per_serving: 60,
    protein_g: 3.5,
    carbs_g: 1,
    fat_g: 4.8,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Buttermilk",
    name_local: "Chaas",
    category: "dairy",
    serving_size_g: 200,
    serving_unit: "ml",
    calories_per_serving: 40,
    protein_g: 2,
    carbs_g: 5,
    fat_g: 1,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Cottage Cheese",
    category: "dairy",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 98,
    protein_g: 11,
    carbs_g: 3.4,
    fat_g: 4.3,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },

  // ============================================================
  // MEAT & EGGS
  // ============================================================
  {
    name: "Chicken Breast",
    category: "meat",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 165,
    protein_g: 31,
    carbs_g: 0,
    fat_g: 3.6,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Chicken Thigh",
    category: "meat",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 209,
    protein_g: 26,
    carbs_g: 0,
    fat_g: 11,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Egg Whole",
    name_local: "Anda",
    category: "meat",
    subcategory: "egg",
    serving_size_g: 50,
    serving_unit: "piece",
    calories_per_serving: 70,
    protein_g: 6,
    carbs_g: 0.6,
    fat_g: 5,
    fiber_g: 0,
    is_veg: false,
    is_egg: true,
    is_vegan: false,
  },
  {
    name: "Egg Whites (3)",
    category: "meat",
    subcategory: "egg",
    serving_size_g: 99,
    serving_unit: "3 whites",
    calories_per_serving: 51,
    protein_g: 10.8,
    carbs_g: 0.7,
    fat_g: 0.2,
    fiber_g: 0,
    is_veg: false,
    is_egg: true,
    is_vegan: false,
  },
  {
    name: "Fish Rohu",
    name_local: "Rohu Machli",
    category: "meat",
    subcategory: "fish",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 97,
    protein_g: 17,
    carbs_g: 0,
    fat_g: 3,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Fish Salmon",
    category: "meat",
    subcategory: "fish",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 208,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 13,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Mutton",
    name_local: "Mutton / Bakra",
    category: "meat",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 258,
    protein_g: 25,
    carbs_g: 0,
    fat_g: 17,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Prawns",
    name_local: "Jhinga",
    category: "meat",
    subcategory: "seafood",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 99,
    protein_g: 24,
    carbs_g: 0.2,
    fat_g: 0.3,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Keema Chicken",
    name_local: "Chicken Keema",
    category: "meat",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 170,
    protein_g: 20,
    carbs_g: 0,
    fat_g: 10,
    fiber_g: 0,
    is_veg: false,
    is_egg: false,
    is_vegan: false,
  },

  // ============================================================
  // NUTS & SEEDS
  // ============================================================
  {
    name: "Almonds",
    name_local: "Badam",
    category: "nut_seed",
    subcategory: "nut",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 58,
    protein_g: 2.1,
    carbs_g: 2.2,
    fat_g: 5.0,
    fiber_g: 1.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Walnuts",
    name_local: "Akhrot",
    category: "nut_seed",
    subcategory: "nut",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 65,
    protein_g: 1.5,
    carbs_g: 1.4,
    fat_g: 6.5,
    fiber_g: 0.7,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Pumpkin Seeds",
    category: "nut_seed",
    subcategory: "seed",
    serving_size_g: 10,
    serving_unit: "tbsp",
    calories_per_serving: 55,
    protein_g: 3,
    carbs_g: 1.3,
    fat_g: 4.5,
    fiber_g: 0.6,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Sunflower Seeds",
    category: "nut_seed",
    subcategory: "seed",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 58,
    protein_g: 2.1,
    carbs_g: 2,
    fat_g: 5.1,
    fiber_g: 0.9,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Flax Seeds",
    name_local: "Alsi",
    category: "nut_seed",
    subcategory: "seed",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 53,
    protein_g: 1.8,
    carbs_g: 2.9,
    fat_g: 4.2,
    fiber_g: 2.7,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Chia Seeds",
    category: "nut_seed",
    subcategory: "seed",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 49,
    protein_g: 1.7,
    carbs_g: 4.2,
    fat_g: 3.1,
    fiber_g: 3.4,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Peanuts",
    name_local: "Moongphali",
    category: "nut_seed",
    subcategory: "nut",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 170,
    protein_g: 7.7,
    carbs_g: 5,
    fat_g: 14,
    fiber_g: 2.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Cashews",
    name_local: "Kaju",
    category: "nut_seed",
    subcategory: "nut",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 55,
    protein_g: 1.8,
    carbs_g: 3,
    fat_g: 4.4,
    fiber_g: 0.3,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Mixed Dry Fruits",
    category: "nut_seed",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 160,
    protein_g: 5,
    carbs_g: 8,
    fat_g: 12,
    fiber_g: 2.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Dates",
    name_local: "Khajoor",
    category: "nut_seed",
    subcategory: "dried_fruit",
    serving_size_g: 16,
    serving_unit: "2 pieces",
    calories_per_serving: 44,
    protein_g: 0.4,
    carbs_g: 11.8,
    fat_g: 0.1,
    fiber_g: 1.3,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Raisins / Dry Grapes",
    name_local: "Kishmish",
    category: "nut_seed",
    subcategory: "dried_fruit",
    serving_size_g: 15,
    serving_unit: "g",
    calories_per_serving: 46,
    protein_g: 0.5,
    carbs_g: 12,
    fat_g: 0.1,
    fiber_g: 0.6,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // PROTEIN SUPPLEMENTS
  // ============================================================
  {
    name: "Whey Protein (1 scoop)",
    category: "protein_supplement",
    serving_size_g: 30,
    serving_unit: "scoop",
    calories_per_serving: 120,
    protein_g: 24,
    carbs_g: 3,
    fat_g: 1.5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Pea Protein (1 scoop)",
    category: "protein_supplement",
    serving_size_g: 30,
    serving_unit: "scoop",
    calories_per_serving: 110,
    protein_g: 22,
    carbs_g: 2,
    fat_g: 1.5,
    fiber_g: 1.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Peanut Butter",
    category: "protein_supplement",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 59,
    protein_g: 2.5,
    carbs_g: 2,
    fat_g: 5,
    fiber_g: 0.6,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
    preferred_brand: "Pintola",
  },

  // ============================================================
  // BEVERAGES
  // ============================================================
  {
    name: "Tea with Milk",
    name_local: "Chai",
    category: "beverage",
    serving_size_g: 150,
    serving_unit: "cup",
    calories_per_serving: 50,
    protein_g: 1.5,
    carbs_g: 6,
    fat_g: 2,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Coffee with Milk",
    name_local: "Coffee",
    category: "beverage",
    serving_size_g: 150,
    serving_unit: "cup",
    calories_per_serving: 55,
    protein_g: 2,
    carbs_g: 5,
    fat_g: 2.5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Green Tea",
    category: "beverage",
    serving_size_g: 200,
    serving_unit: "cup",
    calories_per_serving: 2,
    protein_g: 0,
    carbs_g: 0.5,
    fat_g: 0,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Coconut Water",
    name_local: "Nariyal Paani",
    category: "beverage",
    serving_size_g: 200,
    serving_unit: "ml",
    calories_per_serving: 46,
    protein_g: 0.4,
    carbs_g: 10,
    fat_g: 0.2,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Protein Shake",
    category: "beverage",
    serving_size_g: 300,
    serving_unit: "serving",
    calories_per_serving: 180,
    protein_g: 26,
    carbs_g: 10,
    fat_g: 3,
    fiber_g: 1,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Lassi Sweet",
    name_local: "Meethi Lassi",
    category: "beverage",
    serving_size_g: 200,
    serving_unit: "ml",
    calories_per_serving: 170,
    protein_g: 4,
    carbs_g: 28,
    fat_g: 5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Buttermilk / Chaas",
    name_local: "Chaas",
    category: "beverage",
    serving_size_g: 200,
    serving_unit: "ml",
    calories_per_serving: 40,
    protein_g: 2,
    carbs_g: 5,
    fat_g: 1,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },

  // ============================================================
  // OILS
  // ============================================================
  {
    name: "Olive Oil",
    category: "oil",
    serving_size_g: 14,
    serving_unit: "tbsp",
    calories_per_serving: 119,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Coconut Oil",
    name_local: "Nariyal Tel",
    category: "oil",
    serving_size_g: 14,
    serving_unit: "tbsp",
    calories_per_serving: 121,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 13.5,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Mustard Oil",
    name_local: "Sarson Ka Tel",
    category: "oil",
    serving_size_g: 14,
    serving_unit: "tbsp",
    calories_per_serving: 124,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 14,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // CONDIMENTS
  // ============================================================
  {
    name: "Honey",
    name_local: "Shahad",
    category: "condiment",
    serving_size_g: 21,
    serving_unit: "tbsp",
    calories_per_serving: 64,
    protein_g: 0.1,
    carbs_g: 17,
    fat_g: 0,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Jaggery",
    name_local: "Gur / Bella",
    category: "condiment",
    serving_size_g: 10,
    serving_unit: "g",
    calories_per_serving: 38,
    protein_g: 0.1,
    carbs_g: 9.7,
    fat_g: 0,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Sugar",
    name_local: "Cheeni",
    category: "condiment",
    serving_size_g: 5,
    serving_unit: "tsp",
    calories_per_serving: 20,
    protein_g: 0,
    carbs_g: 5,
    fat_g: 0,
    fiber_g: 0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Pickle (mixed)",
    name_local: "Achaar",
    category: "condiment",
    serving_size_g: 15,
    serving_unit: "tbsp",
    calories_per_serving: 30,
    protein_g: 0.3,
    carbs_g: 2,
    fat_g: 2.3,
    fiber_g: 0.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Coconut Chutney",
    name_local: "Nariyal Chutney",
    category: "condiment",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 55,
    protein_g: 1,
    carbs_g: 3,
    fat_g: 4.5,
    fiber_g: 1.2,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Sambar",
    name_local: "Sambar",
    category: "condiment",
    subcategory: "curry",
    serving_size_g: 100,
    serving_unit: "g",
    calories_per_serving: 65,
    protein_g: 3.2,
    carbs_g: 8,
    fat_g: 2.5,
    fiber_g: 2.0,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },

  // ============================================================
  // SNACKS
  // ============================================================
  {
    name: "Ragi Chips",
    category: "snack",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 135,
    protein_g: 2,
    carbs_g: 18,
    fat_g: 6,
    fiber_g: 1.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Makhana / Fox Nuts",
    name_local: "Makhana",
    category: "snack",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 100,
    protein_g: 3,
    carbs_g: 20,
    fat_g: 0.3,
    fiber_g: 1.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Roasted Chana",
    name_local: "Bhuna Chana",
    category: "snack",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 108,
    protein_g: 6,
    carbs_g: 17,
    fat_g: 1.6,
    fiber_g: 3.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Protein Bar",
    category: "snack",
    serving_size_g: 60,
    serving_unit: "bar",
    calories_per_serving: 210,
    protein_g: 20,
    carbs_g: 22,
    fat_g: 6,
    fiber_g: 3,
    is_veg: true,
    is_egg: false,
    is_vegan: false,
  },
  {
    name: "Energy Ball (homemade)",
    category: "snack",
    serving_size_g: 25,
    serving_unit: "piece",
    calories_per_serving: 90,
    protein_g: 3,
    carbs_g: 10,
    fat_g: 4.5,
    fiber_g: 1.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Khakhra",
    name_local: "Khakhra",
    category: "snack",
    serving_size_g: 20,
    serving_unit: "piece",
    calories_per_serving: 80,
    protein_g: 2.5,
    carbs_g: 12,
    fat_g: 2.5,
    fiber_g: 1.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
  {
    name: "Murmura / Puffed Rice",
    name_local: "Murmura",
    category: "snack",
    serving_size_g: 30,
    serving_unit: "g",
    calories_per_serving: 110,
    protein_g: 2,
    carbs_g: 25,
    fat_g: 0.3,
    fiber_g: 0.5,
    is_veg: true,
    is_egg: false,
    is_vegan: true,
  },
];
